sudo: true
services:
- docker

language: scala
scala:
- 2.12.10
- 2.13.1

jdk:
- openjdk11

script:
- sbt ++$TRAVIS_SCALA_VERSION clean test

after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt ++$TRAVIS_SCALA_VERSION publish; };'
env:
  global:
  - secure: M12wT6/75DEsq0bXmCy8Z5RGI7/mXVlY1sbNoqQG9DSGSDb4ELzJjZxuaFrbSCR7jY6skMcvUOlPUsFKygJZzTT9c9vgk4xvLZcLqPMsK+0MNnko+wy91LWOTToMJTmmYaYy/GnD0Kn3GIdOas8Nmi1Rxgqae43XVnPj5beBIxpe0iosgHBmgOCSsrUsGLaQGWsSMOy/Er8W6oc+Bo5/0A579HOb/7xJ6lNaFctnC+Gb35guVXuuJLj7IQzujY90ejNwSJhMHMH5Hl181UKs5zYGJqz9fM6RsLZ3UFzmclJjziZd7nUJbDa5/56UsV8jLg22R3QPkzquGvgh7Pqv4i0G2H1BsguyQRqjm/ZglvLlxGy4dvlRfprB94ZvRbUwx1WwzOha3I3rs+DKvhVtUUa87mJL8HeCG3ltFzUnB1fdogJnucXxyTq1ZuKLV14pmr7XzsBBwwkg5Teb/eo0SQ4oI9O1BNVPNGI4uGG4LCXKe4ThPAGdMO/SOElND2EmBbH1eS4H3jfpvlc4J38gughxH1mdA7ExxFNLM/FXLSZ6vA5z46xuDJSbp1wEW4pTE7T1kmj9PLlqTrEpnADwtfkbzGT3ztoSYqJ82tgGYdPXLGBczBXeTbW+O9CFcYHu9Wi+zloAZCGkKrau/k9uUdnu1Vn7QMqdBfE43X1WOqs=
  - secure: b4AWvh1kfzt9MQ93CqrBziLpv3lrABfHnuCpvBKMJ9QrjvQD6T0NZxZwB4L5AGePY9f4MvhUMJ9eCRKs9mPbBn0przdW08/epxhEqwvaRv9JfFnefhpLh8IhtYAwphzThkGn3REK1exgalz5Y4Dep1PPP5fqvQCNX7y+Is/wfL5yXC1Nm1pgKgGb5baaFd3CD2U739uE6KBA1jkBE1/1+H+CUO3RtCnUF3Xq2WhDAaQ+nNt3dB6orff8rQ1r/SI4AZ+iUOrEpkHXnrimXP6oBPMLBjoma1WKqnd+72iImyypEwjE6DAvxAg+87Z/7rM+t+Fn0jIo0uRfmwkoFUzKHzuNQWkNElnGlTilcmCkeO0eS+ncntzJv9fINQJCNljeTCv1/PB2C1bWls29Zg6aU/cjOpEx9Lr0ixa7t+KF/VEiSH5SuktusBV5EjYh4loVQgCmmvbUhfL6P+mYUnQh4Tc7N1nM/Vza+0d+7RLp14l7oeenUZ9QaPSxFV2j9dy0KtQcON7ds/PZunl6Hf0QMZCtcCCfrWiyu0ioe5STbA+JH3qhjDUKfBu1kc5r7PvpzNsNIzIcQnFEnOT1uqVOSh9DZUxsAalSNmdAZfOoyq+MlRptYy4h/SclcGuVsxz+b4kkE/x4vl1/xbwYruWzSzhQ6gqSlq3T8eWP+glUASk=
